version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    volumes:
      - frontend-data:/frontend-app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/backend-app

volumes:
  backend-data:
  frontend-data: